Add missing scene attribute _los_factors in scene.py
Fix error: "Scene object has no attribute '_los_factors'", when calling scene.los_rotation_factors